name       : valgrind
version    : 3.15.0
release    : 10
source     :
    - ftp://sourceware.org/pub/valgrind/valgrind-3.15.0.tar.bz2 : 417c7a9da8f60dd05698b3a7bc6002e4ef996f14c13f0ff96679a16873e78ab1
homepage   : https://valgrind.org
license    : GPL-2.0-or-later
optimize   : no-bind-now
summary    : Valgrind (Instrumentation framework for analysis tools)
component  : programming.tools
patterns   :
    - docs : /usr/share/doc
rundeps    :
    - glibc-dbginfo
description: |
    Valgrind is an instrutmentation framework for building dynamic analysis tools. It can detect memory management and threading bugs, along with profiling in detail.  Extremely useful for debugging.
setup      : |
    %configure CFLAGS="$CFLAGS -fno-stack-protector" CXXFLAGS="$CXXFLAGS -fno-exceptions"
build      : |
    %make
install    : |
    %make_install
