name       : valgrind
version    : 3.17.0
release    : 16
source     :
    - ftp://sourceware.org/pub/valgrind/valgrind-3.17.0.tar.bz2 : ad3aec668e813e40f238995f60796d9590eee64a16dff88421430630e69285a2
license    : GPL-2.0-or-later
component  : programming.tools
homepage   : https://valgrind.org/
summary    : Instrumentation framework for analysis tools
description: |
    Valgrind is an instrutmentation framework for building dynamic analysis tools. It can detect memory management and threading bugs, along with profiling in detail.  Extremely useful for debugging.
optimize   :
    - no-bind-now
patterns   :
    - docs : /usr/share/doc
rundeps    :
    - glibc-dbginfo
setup      : |
    %configure CFLAGS="$CFLAGS -fno-stack-protector" CXXFLAGS="$CXXFLAGS -fno-exceptions"
build      : |
    %make
install    : |
    %make_install
